SELECT A.ID, IFNULL(SUM(A.AMOUNT),0) AS TOTAL_PRICE
FROM
(SELECT GAME_USERS.ID, PAYMENTS.ID as P_ID, PAYMENTS.AMOUNT, PAYMENT_TYPE
FROM GAME_USERS
LEFT JOIN PAYMENTS
ON GAME_USERS.ID = PAYMENTS.USER_ID) as A
GROUP BY A.ID
ORDER BY A.ID;