SELECT B.ID as USER_ID
FROM 
(SELECT A.ID, A.ID1
FROM 
(SELECT GAME_USERS.ID, GAME_USERS.DISTANCE, GAME_USERS.TIME_SPENT, GAME_USERS.BEST_DATE, FRIENDS.ID1, FRIENDS.ID2
FROM GAME_USERS LEFT JOIN FRIENDS
ON GAME_USERS.ID = FRIENDS.ID1 OR GAME_USERS.ID = FRIENDS.ID2) as A
GROUP BY A.ID
HAVING A.ID1 IS NULL OR A.ID1 = '') as B